name: Test and Deploy to Vercel

on:
  push:
    branches:
      - main   # This workflow will run when changes are pushed to the main branch
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python 3.9 (or other versions if needed)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the tests
      - name: Run tests
        run: |
          python test.py  # Running test.py script

      # Archive test results if needed (optional)
      - name: Archive test results
        if: failure()  # Only if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./test-output/

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Only run this job if the tests pass
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Node.js (required for Vercel)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Adjust Node.js version as per your project

      # Install Vercel CLI
      - name: Install Vercel CLI
        run: npm install -g vercel

      # Authenticate Vercel using a token
      - name: Vercel Authentication
        run: vercel login --token ${{ secrets.VERCEL_TOKEN1 }}

      # Deploy to Vercel
      - name: Deploy to Vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN1 }}